import Head from 'next/head'
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from '@/lib/query'
import Product from '@/Components/product'
import { Gallery } from '@/styles/Gallery'
import { Loading, Error } from '@/Components/Messages'
import { logo } from '@/public/logo.svg'

export default function Home() {
  const [result] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = result;
  console.log(result)
  if (fetching) return <Loading />
  if (error) return <Error error={error.message} />
  const products = data.products.data;
  return (
    <>
      <Head>
        <title>Webshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/public/logo.svg" />
        <link rel="icon" type="image/png" href="/public/favicon.png" />
      </Head>
      <main>
        <Gallery>
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>
    </>
  )
}
